components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: integer
          example: 1
        name:
          type: string
          required: true
          example: Quentinha simples
        value:
          type: number
          required: true
          example: 20
        discount:
          type: number
          required: true
          description: porcentagem
          example: 4
        discountedValue:
          type: number
          required: true
          description: valor com porcentagem de desconto
          example: 19.20
        preparationTime:
          type: number
          required: true
          description: Tempo de preparo em minutos
          example: 30
        status:
          type: string
          required: true
          enum: [Ativo,Inativo]
          example: Ativo
        supplier:
          $ref: "#/components/schemas/User"
        createdAt:
          type: string
          example: 2023-07-20T02:27:59.751Z
        updatedAt:
          type: string
          example: 2023-07-20T02:27:59.751Z
