version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_ena_food
    command: bash -c "yarn start-dev"
    restart: always
    working_dir: /home/app
    volumes:
      - .:/usr/app
    depends_on:
      app_mongodb:
        condition: service_healthy
    env_file:
      - .env
    ports:
      -  ${PORT}:${PORT}
    links:
      - app_mongodb

  app_mongodb:
    image: mongo:6-jammy
    container_name: mongo_ena_food
    restart: always
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      timeout: 10s
      retries: 10
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db

volumes:
  app_volume:
    driver: local
  dbdata6:
